from sqlalchemy import inspect, text
from app.database import engine


NEW_COLUMNS = {
    "employee_type": "VARCHAR(50)",
    "work_location": "VARCHAR(150)",
    "date_of_exit": "TIMESTAMP",

    "pf_applicable": "BOOLEAN NOT NULL DEFAULT FALSE",
    "esic_applicable": "BOOLEAN NOT NULL DEFAULT FALSE",

    "basic_salary": "DOUBLE PRECISION",
    "gross_salary": "DOUBLE PRECISION",
    "ctc": "DOUBLE PRECISION",

    "hra": "DOUBLE PRECISION",
    "conveyance_allowance": "DOUBLE PRECISION",
    "other_allowance": "DOUBLE PRECISION",

    "employee_pf_contribution": "DOUBLE PRECISION",
    "employer_pf_contribution": "DOUBLE PRECISION",

    "employee_esic_contribution": "DOUBLE PRECISION",
    "employer_esic_contribution": "DOUBLE PRECISION",

    "blood_group": "VARCHAR(20)",
    "emergency_contact_name": "VARCHAR(150)",
    "emergency_contact_mobile": "VARCHAR(30)",
    "emergency_contact_relation": "VARCHAR(50)",
}


def migrate():
    inspector = inspect(engine)

    if "employee_master" not in inspector.get_table_names():
        print("employee_master table not found")
        return

    existing = {
        column["name"]
        for column in inspector.get_columns("employee_master")
    }

    with engine.begin() as connection:
        for column_name, column_type in NEW_COLUMNS.items():
            if column_name in existing:
                print(f"SKIP: {column_name}")
                continue

            connection.execute(
                text(
                    f'ALTER TABLE employee_master '
                    f'ADD COLUMN "{column_name}" {column_type}'
                )
            )

            print(f"ADDED: {column_name}")

    print("EmployeeMaster migration completed.")

def create_employee_documents():
    inspector = inspect(engine)

    if "employee_documents" in inspector.get_table_names():
        print("SKIP: employee_documents table already exists")
        return

    with engine.begin() as connection:
        connection.execute(
            text(
                """
                CREATE TABLE employee_documents (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    employee_id VARCHAR(30) NOT NULL,
                    document_type VARCHAR(100) NOT NULL,
                    document_name VARCHAR(200),
                    document_number VARCHAR(100),
                    file_url TEXT,
                    issue_date TIMESTAMP,
                    expiry_date TIMESTAMP,
                    remarks TEXT,
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    uploaded_by VARCHAR(30),
                    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_employee_documents_employee
                        FOREIGN KEY (employee_id)
                        REFERENCES employee_master(id)
                )
                """
            )
        )

        connection.execute(
            text(
                """
                CREATE INDEX ix_employee_documents_employee_id
                ON employee_documents (employee_id)
                """
            )
        )

    print("CREATED: employee_documents")

if __name__ == "__main__":
    migrate()
    create_employee_documents()
